# Generated by Django 4.2.22 on 2026-02-04 02:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tareas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('calificado', 'Calificado')], default='pendiente', max_length=15)),
                ('calificacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario_docente', models.TextField(blank=True, default='')),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entregas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to=tareas.models.task_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar', 'txt'])])),
                ('url_recurso', models.URLField(blank=True, default='', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='borrador', max_length=10)),
                ('puntos_maximos', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('permite_tardias', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=tareas.models.submission_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar', 'txt', 'py', 'js', 'html', 'css', 'java', 'cpp', 'c'])])),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_entrega_tardia', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='tareas.submission')),
            ],
            options={
                'verbose_name': 'Archivo de Entrega',
                'verbose_name_plural': 'Archivos de Entrega',
                'db_table': 'archivos_entrega',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tareas.task'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('task', 'student')},
        ),
    ]
