# Generated by Django 4.2.22 on 2026-02-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_email_logs_fecha_e_idx_email_logs_fecha_e_dcc5da_idx_and_more'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Materia a la que pertenece esta tarea', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='users.materia', verbose_name='Materia'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['materia', 'estado'], name='tareas_materia_21acec_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['docente', 'estado'], name='tareas_docente_960979_idx'),
        ),
    ]
