# Generated by Django 4.2.22 on 2026-02-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_email_logs_fecha_e_idx_email_logs_fecha_e_dcc5da_idx_and_more'),
        ('tareas', '0004_alter_task_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='materia',
            field=models.ForeignKey(help_text='Materia a la que pertenece esta tarea', on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='users.materia', verbose_name='Materia'),
        ),
    ]
