# Generated by Django 4.2.22 on 2026-05-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_task_materia'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tareas_materia_21acec_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='materia',
        ),
    ]
