# Generated by Django 4.2.22 on 2026-02-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emaillog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_fecha_e_dcc5da_idx',
            old_name='email_logs_fecha_e_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_destina_608848_idx',
            old_name='email_logs_destina_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_tipo_280941_idx',
            old_name='email_logs_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_estado_e4b9a7_idx',
            old_name='email_logs_estado_idx',
        ),
    ]
